name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v1

      - name: install python tools
        run: pip install markdown

      - name: change script permissions
        run: chmod +x ./cbr ./website

      - name: create build directory
        run: mkdir build

      - name: build the site
        run: ./website build

      - name: Publish files to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build